replicaCount: 1
tag: 1
#namespace: default
service:
  type: NodePort
  name: micro-geo-svc
  nodePortTst: 30188
  nodePortPrd: 30183

ImageName: hhssaaffii/micro-geo

port: 8092
portTest: 8094

fullName: micro-geo

appName: micro-geo

portNumber: 8092
host: test.evbricks.com

image: ##DOCKER_REGISTRY##/hhssaaffii/micro-geo

artifactory:
  name: artifactory

secretKeyRef:
  name: <db-name>

